/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "home": [],
    "student.index": [],
    "student.create": [],
    "student.store": [],
    "student.update": [
        {
            "name": "student",
            "required": true
        }
    ],
    "student.destroy": [
        {
            "name": "student",
            "required": true
        }
    ],
    "course.index": [],
    "course.create": [],
    "course.store": [],
    "course.update": [
        {
            "name": "course",
            "required": true
        }
    ],
    "course.destroy": [
        {
            "name": "course",
            "required": true
        }
    ],
    "exam.index": [],
    "exam.create": [],
    "exam.store": [],
    "exam.update": [
        {
            "name": "exam",
            "required": true
        }
    ],
    "exam.destroy": [
        {
            "name": "exam",
            "required": true
        }
    ],
    "result.index": [
        {
            "name": "exam",
            "required": true
        }
    ],
    "result.store": [
        {
            "name": "exam",
            "required": true
        }
    ],
    "question.index": [],
    "question.create": [],
    "question.store": [],
    "question.update": [
        {
            "name": "question",
            "required": true
        }
    ],
    "question.destroy": [
        {
            "name": "question",
            "required": true
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
